apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx 
spec:
  replicas: 3 
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
