apiVersion: batch/v1
kind: Job
metadata:
  name: job-redis
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: harshal0812/job-redis
      restartPolicy: OnFailure

