apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: printhello
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 100

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          restartPolicy: OnFailure

