apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  template:
    spec:
      containers:
        - name: math-container
          image: ubuntu
          command: ["expr","10","+","24"]
      restartPolicy: Never
